services:
  db:
    image: public.ecr.aws/u8i2f6l2/integration/db:postgres-16
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env  # 여기에 .env 파일 설정

  redis:
    image: public.ecr.aws/u8i2f6l2/integration/db:redis-latest
    ports:
      - "6379:6379"
    restart: always
    env_file:
      - .env  # 여기에 .env 파일 설정

  celery-worker:
    image: public.ecr.aws/u8i2f6l2/integration/db:worker-latest
    build:
      context: ./backend
    depends_on:
      - db
      - redis
    restart: always
    env_file:
      - .env  # 여기에 .env 파일 설정
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  celery-beat:
    image: public.ecr.aws/u8i2f6l2/integration/db:beat-latest
    depends_on:
      - db
      - redis
    restart: always
    env_file:
      - .env  # 여기에 .env 파일 설정
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  app-db-data: