services:
  db:
    image: 593793035161.dkr.ecr.ap-northeast-2.amazonaws.com/integration/db:postgres-16
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env

  redis:
    image: 593793035161.dkr.ecr.ap-northeast-2.amazonaws.com/integration/db:redis-latest
    ports:
      - "6379:6379"
    restart: always

  celery-worker:
    image: 593793035161.dkr.ecr.ap-northeast-2.amazonaws.com/integration/db:worker-latest
    command: [ "celery", "-A", "app.celery.worker", "worker", "--loglevel=info" ]
    depends_on:
      - redis
      - db
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  celery-beat:
    image: 593793035161.dkr.ecr.ap-northeast-2.amazonaws.com/integration/db:beat-latest
    command: [ "celery", "-A", "app.celery.worker", "beat", "--loglevel=info" ]
    depends_on:
      - redis
      - db
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  app-db-data: